### ISSUE TITLE
Downloading entire database and process it into PNG format and turn to pixel data

### ISSUE THREAD

**Issue by albertli354** [albertli354/Final-Project-Info370#1]

**Comment by kml27** [comment]
I already downloaded and unzipped it (took over 3hr, inode size or fs fragmentation?). It is in PNG already.

**Comment by emilyding0601** [comment]
They are already PNG. Thanks.

**Comment by emilyding0601** [comment]
Reopen the issues: process the pixel data *from* PNG

**Comment by emilyding0601** [comment]
process 5, 10, 20, 30 writers for tensorflow model
